### ISSUE TITLE
fawry integration errors

### ISSUE THREAD

**Issue by MarwaMourad15** [Nafezly/payments#6]
Try to use fawry:
"returnUrl" missing in "chargeRequest" object, and 
FawryPay.checkout missing "configuration" object 
{
                    locale : \"en\",  //default en
                    mode: DISPLAY_MODE.POPUP,  //required, allowed values [POPUP, INSIDE_PAGE, SIDE_PAGE , SEPARATED]
                }

**Comment by peter-tharwat** [comment]
hello marwa , 
can you share test keys to check ,
at ptharwat@gmail.com

**Comment by NafezlyDotCom** [comment]
Resolved
